carts_get:
  path: /carts
  controller: App\UI\Controller\Carts\GetCartsController
  methods: GET

carts_get_by_id:
  path: /carts/{id}
  controller: App\UI\Controller\Carts\GetCartByIdController
  methods: GET
  requirements:
    id: '%routing.uuid%'

carts_create:
  path: /carts
  controller: App\UI\Controller\Carts\CreateCartController
  methods: POST

carts_update:
  path: /carts
  controller: App\UI\Controller\Carts\UpdateCartController
  methods: PUT

carts_confirm:
  path: /carts/{id}/confirm
  controller: App\UI\Controller\Carts\ConfirmCartByIdController
  methods: PUT
  requirements:
    id: '%routing.uuid%'

carts_delete:
  path: /carts/{id}
  controller: App\UI\Controller\Carts\DeleteCartByIdController
  methods: DELETE
  requirements:
    id: '%routing.uuid%'
