# FAVICON (avoid console error)
favicon:
  path: /favicon.ico
  controller:
  methods: GET

products:
  resource: routes/products.yaml
  prefix: /api/

orders:
  resource: routes/orders.yaml
  prefix: /api/
